- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-activemq-helm-lint
        - nebulous-activemq-build-container-images
        - nebulous-activemq-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-activemq-helm-lint
        - nebulous-activemq-upload-container-images
        - nebulous-activemq-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-activemq-promote-container-images
