name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-activemq-broker-control-plane:
    name: Build and push activemq-broker control-plane
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: docker-control-plane
      image-name: activemq-broker
    secrets: inherit
  build-and-push-activemq-broker-app-cluster:
    name: Build and push activemq-broker app-cluster
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: docker-app-cluster
      image-name: activemq-broker-app-cluster
    secrets: inherit